In [1]:

import torch
from torch import nn
import numpy as np

In [2]:
# 12. DEEP NEURAL NETWORK ARCHITECTURE FOR REGRESSION
class linear_reg(nn.Module):
    def __init__(self):
        super().__init__()
        # Input Layer: Takes 23 encoded features and expands to 100 hidden units
        self.linear1 = nn.Linear(23, 100)
        self.bn1 = nn.BatchNorm1d(100)        # Stabilizes learning and accelerates training
        self.act1 = nn.ReLU()                  # Introduces non-linearity
        
        # Hidden Layer: Compresses 100 units down to 50 hidden units
        self.linear2 = nn.Linear(100, 50)
        self.bn2 = nn.BatchNorm1d(50)         # Normalizes the activations of the second layer
        self.act2 = nn.ReLU()                  # Introduces non-linearity
        self.dropout = nn.Dropout(p=0.2)       # Randomly deactivates 20% of neurons to prevent overfitting
      
        # Output Layer: Maps 50 features down to 1 continuous target prediction (House Price)
        self.linear_out = nn.Linear(50, 1)

    def forward(self, x):
        # Pass data through the first block (Linear -> BatchNorm -> ReLU)
        x = self.linear1(x)
        x = self.bn1(x)
        x = self.act1(x)
        
        # Pass data through the second block with Dropout regularization
        x = self.dropout(x)
        x = self.linear2(x)
        x = self.bn2(x) 
        x = self.act2(x)
        x = self.dropout(x)
        
        # Final output projection
        return self.linear_out(x)

In [3]:
model = linear_reg()
model.state_dict()

OrderedDict([('linear1.weight',
              tensor([[ 0.1306,  0.0786, -0.1377,  ..., -0.0230,  0.1687,  0.1596],
                      [ 0.1513, -0.0866, -0.0803,  ...,  0.1465,  0.1591,  0.1319],
                      [ 0.0647,  0.1950, -0.1218,  ...,  0.1286, -0.0099, -0.0499],
                      ...,
                      [ 0.0978, -0.0859,  0.1750,  ..., -0.0813,  0.1943,  0.0303],
                      [-0.0026,  0.1718,  0.1980,  ..., -0.0401,  0.2020, -0.0492],
                      [ 0.0323,  0.1279, -0.0125,  ...,  0.0318,  0.0279, -0.0776]])),
             ('linear1.bias',
              tensor([ 0.0643, -0.2026,  0.1187,  0.1683,  0.1949,  0.1903, -0.1743, -0.0413,
                       0.1928,  0.2005, -0.0292,  0.1495,  0.0571, -0.0480, -0.0227,  0.0821,
                       0.1882, -0.1709, -0.1851,  0.0977,  0.2043, -0.0686,  0.0021, -0.0804,
                       0.0466, -0.0939,  0.0586, -0.1908,  0.0482,  0.1865,  0.1743,  0.1167,
                       0.097

In [4]:
dic = torch.load("model.pt")

In [5]:
model.load_state_dict(dic)
model.state_dict()

OrderedDict([('linear1.weight',
              tensor([[-0.3080, -0.1007, -0.2533,  ...,  0.2852,  0.0711, -0.3892],
                      [-0.1167, -0.2273,  0.0176,  ...,  0.3041, -0.0968, -0.4241],
                      [-0.4127, -0.0477,  0.1134,  ..., -0.0145,  0.0350, -0.0094],
                      ...,
                      [ 0.4478,  0.1639, -0.1033,  ...,  0.0344, -0.0769, -0.0554],
                      [ 0.4915,  0.0402, -0.1487,  ...,  0.2156,  0.3829, -0.1198],
                      [ 0.4772, -0.0061,  0.0660,  ..., -0.0284,  0.0153, -0.0195]])),
             ('linear1.bias',
              tensor([-1.1181e-01, -1.7648e-01, -1.5190e-01, -1.1251e-01, -2.1669e-01,
                       1.2208e-01, -1.7296e-01,  8.5565e-02, -1.3827e-01,  2.1209e-01,
                       6.7581e-02,  1.4809e-01,  9.3040e-02, -1.4712e-01,  1.9361e-01,
                      -4.5964e-02, -1.0129e-01, -1.2787e-01, -2.9306e-02, -1.7296e-01,
                      -1.9342e-01, -2.1904e-02,  3.0192e

In [6]:
x = np.load("dataset.npy")

In [7]:
torch.tensor(x , dtype=torch.float32 , device="cuda")

tensor([[-1.1598,  0.5996,  1.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 1.1607,  4.7530,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.6188,  3.6348,  0.0000,  ...,  0.0000,  1.0000,  0.0000],
        ...,
        [-0.1669,  4.0551,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 1.5201,  1.9309,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.3607,  3.1088,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],
       device='cuda:0')

In [8]:
model.eval()
with torch.inference_mode():
    model.to("cuda")
    y_pred =  model(torch.tensor(x , dtype=torch.float32 , device="cuda"))

In [9]:
import joblib
scaler_y = joblib.load("scaler_y.pt")

In [10]:
scaler_y.inverse_transform(y_pred.cpu().numpy())

array([[ 279959.3 ],
       [ 978011.6 ],
       [ 777185.9 ],
       [ 237728.58],
       [1045648.2 ],
       [ 869502.06],
       [ 810712.3 ],
       [ 707666.  ],
       [ 182084.11],
       [ 517963.84],
       [ 322893.16],
       [ 633208.6 ],
       [ 691382.6 ],
       [ 452974.06],
       [ 835819.8 ],
       [1025156.8 ],
       [ 735532.25],
       [ 244421.73],
       [ 416700.16],
       [ 662347.7 ],
       [ 591769.3 ],
       [ 734115.4 ],
       [ 370056.66],
       [ 526459.94],
       [ 230001.89],
       [ 658280.9 ],
       [ 750936.44],
       [ 508245.5 ],
       [ 419828.94],
       [ 440756.06],
       [ 814849.  ],
       [ 889579.06],
       [ 926403.4 ],
       [ 273195.12],
       [ 696871.8 ],
       [ 647355.1 ],
       [ 294247.6 ],
       [ 600179.4 ],
       [ 540209.9 ],
       [ 200266.36],
       [ 559717.8 ],
       [ 694547.06],
       [ 659341.  ],
       [ 399354.44],
       [ 478127.75],
       [ 723941.06],
       [ 305086.47],
       [10232